### ISSUE TITLE
Not a code Problem - cant use the api on mineid.org

### ISSUE THREAD

**Issue by Pfannkuchensack** [MineID/MineID#1]
Hey...
I have a Problem with the api. i got only 403 error.
i searched for doku or a example but fund only the "python-social-auth", but I can not find my error or how it should be. I got the token and try todo a api/user request.
somebody can help me?

**Comment by caioariede** [comment]
Hi @Pfannkuchensack ,

Did you follow these steps?
1. Create an account in MineID.org
2. Register a new application
3. Use the Client ID and Client Secret settings given for your application

**MineID.org** is an _OAuth2 provider_, which means you need an _OAuth2 client_ to communicate with it.

**python-social-auth** is an _OAuth2 client_, you can find more info about it in their docs:

http://psa.matiasaguirre.net/docs/backends/mineid.html

**Comment by Pfannkuchensack** [comment]
1.,2.,3. done. But i use my own Script for the OAuth but i cant get the user infos.
Now i let the user type the minecraft name and save it.
