### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by jacobwgillespie** [MineID/MineID#10]
It appears that the website is down.  Is this service dead?  Are you planning on bringing it back?

If not, might you be looking for someone to take it over?  I run a similar Minecraft OAuth provider and would be interested in reviving / extending MineID.

**Comment by Foorack** [comment]
@jacobwgillespie It most certainly does. The repository hasn't been updated for years. As of writing the website is also dead. I have tried contacting the author via email without response. What is the other Minecraft OAuth service you run? Are you still interested in working on this kind of project?

**Comment by jacobwgillespie** [comment]
@Foorack the project is located at https://github.com/the-obsidian/mc-discourse-sso.

Right now it's specifically customized to work with the Discourse forum login system, but it would be fairly easy to extend to support OAuth in general.  For now it's just used within the Obsidian private server community.
