### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by ghost** [MineID/MineID#8]
https://www.mineid.org

It will be renewed?

**Comment by ghost** [comment]
If you don't have founds for this project. Please contact me `moldcraft[at]email.com`, I can buy one ssl certificate with bitcons from namecheap.com (it will be a donation).

I already use this project in production so I really need it (but I don't want to install it on my own host, I want to use mineid.org)

**Comment by ghost** [comment]
Anyone?

(now users can't login on my site)

**Comment by caioariede** [comment]
Hi @moldcraft 

I'm contact the person responsible for the certificate. I'll keep you informed.

Thank you for reporting it.

**Comment by ghost** [comment]
1. Any updates?
2. I am the only one user of mineid.org, nobody else is complaining that it's not working?

**Comment by daronstinnett** [comment]
Hi @moldcraft 

I'm looking into this now and hope to have it resolved within the next 48 hours.
- Daron

**Comment by daronstinnett** [comment]
@moldcraft @caioariede the SSL issue is fixed

**Comment by ghost** [comment]
Thank you
